version: '3'
services:
  e-commerce-api:
    container_name: e-commerce-api
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
    links:
     - mongo
  mongo:
    container_name: mongoDB
    image: mongo
    ports:
      - "27017:27017"
